<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Carter" />
		<PackageReference Include="MediatR" />
		<PackageReference Include="Microsoft.OpenApi" />
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Application\Framework.Application.Shared\Framework.Application.Shared.csproj" />
	</ItemGroup>
	
</Project>
