<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="AutoMapper" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\Application\Framework.Application.Abstraction\Framework.Application.Abstraction.csproj" />
		<ProjectReference Include="..\..\..\Domain\Framework.Domain.Abstraction\Framework.Domain.Abstraction.csproj" />
	</ItemGroup>
	
</Project>
