<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Microsoft.Extensions.Localization" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Framework\Domain\Framework.Domain.Shared\Framework.Domain.Shared.csproj" />
	</ItemGroup>
	
</Project>
