<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Carter" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Framework\Presentation\Framework.Presentation.Shared\Framework.Presentation.Shared.csproj" />
		<ProjectReference Include="..\Identity.Application\Identity.Application.csproj" />
	</ItemGroup>
	
</Project>
